wait for report

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -102,7 +102,19 @@ jobs:
       - run: npx nx run react:test --coverage
         working-directory: frontend
 
-      - name: Organize report by date
+      - name: Check for coverage report existence
+        run: |
+          timeout=120 # 2 minutes in seconds
+          while [ ! -d "frontend/apps/react/reports/coverage/" ]; do
+            if [ $SECONDS -ge $timeout ]; then
+              echo "Timeout reached. Coverage reports not found."
+              exit 1 # Exit the script with an error
+            fi
+            echo "Waiting for coverage reports to be generated..."
+            sleep 5
+        done      - name: Organize report by date
+
+      - name: Organize reports by date
         run: |
           REPORT_DIR="coverage_reports/$(date +%Y%m%d-%H%M%S)"
           mkdir -p "$REPORT_DIR"
